### ISSUE TITLE
Removed Events you created are still displayed in right drawer My Events

### ISSUE THREAD

**Issue by PaulMEdwards** [Lambda-School-Labs/neighborhood-chef-fe#170]
I Created, then Removed the June 24th event titled "blah", but it still shows in the My Events list in the right drawer.

![image](https://user-images.githubusercontent.com/153847/85822069-d51c4600-b72e-11ea-84af-5893cf99cf4a.png)

**Comment by kyle-richardson** [comment]
This is actually expected behavior to some extent.

The “remove” button is meant to only remove you from the invited list on the event, not delete the event.  Anyone can remove any event, and there is a prompt about how only the owner can reinvite them.

However, there does need to be a way for the organizer to delete the event instead of just remove like other invited users.

Simplest way to do this would be to code conditional delete button to show in place of remove and perform event deletion when the event creator accesses.
